"""
Finding model for vulnerability findings and triage results.
"""
from sqlalchemy import Column, String, Text, DateTime, Boolean, Numeric
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.sql import func
import uuid
import enum

from database import Base


class Severity(str, enum.Enum):
    """Finding severity levels."""
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class Exploitability(str, enum.Enum):
    """Finding exploitability assessment."""
    PROVEN = "PROVEN"
    LIKELY = "LIKELY"
    POSSIBLE = "POSSIBLE"
    UNLIKELY = "UNLIKELY"


class Finding(Base):
    """
    Vulnerability finding from triage analysis.

    Generated by Triage Agent after correlating evidence and scoring severity.
    """

    __tablename__ = "findings"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    run_id = Column(UUID(as_uuid=True), nullable=False, index=True)

    # Finding details
    title = Column(String(500), nullable=False)
    description = Column(Text, nullable=False)
    severity = Column(String(20), nullable=False, index=True)  # CRITICAL, HIGH, MEDIUM, LOW, INFO
    cvss_score = Column(Numeric(3, 1), nullable=True)  # 0.0 to 10.0
    exploitability = Column(String(20), nullable=True)  # PROVEN, LIKELY, POSSIBLE, UNLIKELY

    # Evidence chain
    evidence_ids = Column(JSONB, nullable=False)  # [evidence_ids] proving this finding

    # Validation (V2 requirement: findings must be validated to appear in report)
    validated = Column(Boolean, default=False, nullable=False, index=True)
    validator_id = Column(UUID(as_uuid=True), nullable=True)  # ValidatorAgent that confirmed
    validated_at = Column(DateTime(timezone=True), nullable=True, index=True)

    # False positive flagging
    is_false_positive = Column(Boolean, default=False, nullable=False)
    false_positive_reason = Column(Text, nullable=True)
    verified_by = Column(UUID(as_uuid=True), nullable=True)

    # Framework mappings
    owasp_mappings = Column(JSONB, server_default='[]')  # ["A01:2021", "A03:2021", ...]
    nist_mappings = Column(JSONB, server_default='[]')
    mitre_mappings = Column(JSONB, server_default='[]')  # ["T1190", "T1078", ...]

    # Metadata
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    def __repr__(self):
        return f"<Finding {self.title} ({self.severity})>"
