"""
Test Plan and Action models for defining penetration test execution.
"""
from sqlalchemy import Column, String, Text, DateTime, CheckConstraint, Integer
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.sql import func
import uuid
import enum

from database import Base


class TestPlan(Base):
    """
    Test Plan generated by agent or manually created.

    Contains:
    - stages: List of test stages with actions
    - framework_mappings: Mappings to OWASP, NIST, MITRE ATT&CK
    - risk_summary: Count of L0-L3 actions
    """

    __tablename__ = "test_plans"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    scope_id = Column(UUID(as_uuid=True), nullable=False, index=True)

    # Plan content (generated by agent)
    stages = Column(JSONB, nullable=False)  # [{stage_id, name, actions: [...]}, ...]
    framework_mappings = Column(JSONB, nullable=False, server_default='{}')  # {owasp: [...], nist: [...], mitre: [...]}
    risk_summary = Column(JSONB, nullable=False, server_default='{}')  # {l0_count: 15, l1_count: 30, ...}

    # Approval
    approved_at = Column(DateTime(timezone=True), nullable=True)
    approved_by = Column(UUID(as_uuid=True), nullable=True)
    approval_signature = Column(Text, nullable=True)  # RSA signature

    # Metadata
    generated_by = Column(String(50), default="AGENT", nullable=False)  # AGENT or USER
    generated_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Constraint: Either all approval fields are NULL or all are NOT NULL
    __table_args__ = (
        CheckConstraint(
            """
            (approved_at IS NULL AND approved_by IS NULL) OR
            (approved_at IS NOT NULL AND approved_by IS NOT NULL)
            """,
            name="plan_approved_check"
        ),
    )

    def __repr__(self):
        approval_status = "APPROVED" if self.approved_at else "PENDING_APPROVAL"
        return f"<TestPlan {self.id} ({approval_status})>"


class ActionStatus(str, enum.Enum):
    """Action execution status."""
    PENDING = "PENDING"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    REJECTED = "REJECTED"


class RiskLevel(str, enum.Enum):
    """Action risk levels."""
    L0 = "L0"  # Passive reconnaissance
    L1 = "L1"  # Active scanning
    L2 = "L2"  # Exploitation
    L3 = "L3"  # Critical impact


class Action(Base):
    """
    Individual action in a test plan.

    Each action represents a single penetration testing step (e.g., Nmap scan, SQL injection test).
    """

    __tablename__ = "actions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    plan_id = Column(UUID(as_uuid=True), nullable=False, index=True)

    # Action definition
    action_id = Column(String(255), nullable=False)  # Unique within plan (e.g., "action-001")
    description = Column(Text, nullable=False)
    method = Column(String(100), nullable=False)  # Tool: nmap, burp, sqlmap, whois, etc.
    target = Column(String(255), nullable=False)  # Target system/URL
    parameters = Column(JSONB, nullable=False, server_default='{}')  # Tool-specific parameters
    risk_level = Column(String(5), nullable=False, index=True)  # L0, L1, L2, L3

    # Dependencies
    prerequisites = Column(JSONB, nullable=False, server_default='[]')  # [action_ids] that must complete first

    # Execution state
    status = Column(String(50), default=ActionStatus.PENDING.value, nullable=False, index=True)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    def __repr__(self):
        return f"<Action {self.action_id} ({self.method} on {self.target})>"
